<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' lang='pt-br'>

<head>
    <META NAME='ROBOTS' CONTENT='NOINDEX, NOFOLLOW'>
    <title>Nagem.com.br / <?= htmlspecialchars($this->escapeHtml($subject)) ?></title>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
    <meta name=viewport content='width=device-width, initial-scale=1' />
    <style type='text/css'>
        body {
            font-family: 'Arial';
        }
    </style>
    <?php
    function formatarValorMonetario(string $valor): string
    {
        // Substitui a vírgula por ponto e converte em número float
        $valorFloat = floatval(str_replace(',', '.', $valor));

        // Formata o número com separadores de milhar e decimal no padrão brasileiro
        return "R$ " . number_format($valorFloat, 2, ',', '.');
    }
    ?>
</head>

<body bgcolor='#f2f2f2' style='text-align:center;'>
    <table border='0' cellpadding='0' cellspacing='0' width='640' align='center' style='background-color:#ffffff; width:620px; margin:0 auto;'>
        <tr style='height: 75px;'>
            <td colspan='3' style='background-color:#0046B4;color:#ffffff;text-align:center;'>
                <table align='center' style='width: 94%; '>
                    <td><img style='float: left: padding 10px' src='http://trunk.nagem.com.br/util/artefatos/asset/n/13281721392427/img/layout/email/logoNagem.png' height='25' /></td>
                    <td style='width: 93px; padding-left: 20px;'>
                        <table>
                            <tr>
                                <td valign='top'>
                                    <p style='font-size: 30px; margin: 5px; font-weight: bold; color: #f4f4f4;'>34</p>
                                </td>
                                <td valign='top' style='text-align: left; width: 60px; font-size: 10px; color: #f4f4f4; padding: 11px 0; line-height: 12px;'>Anos de mercado</td>
                            </tr>
                        </table>
                    </td>
                    <td><img src='http://trunk.nagem.com.br/util/artefatos/asset/n/1121721392427/img/layout/email/img-separador-menu.png' height='25' /></td>
                    <td>
                        <a href='http://trunk.nagem.com.br/institucional/nossaslojas/' target='_blank' style='text-decoration: none;'>
                            <table>
                                <tr>
                                    <td valign='top'>
                                        <p style='font-size: 29px; margin: 5px; font-weight: bold; color: #f4f4f4;'>55</p>
                                    </td>
                                    <td valign='top' style='text-align: left; width: 60px; font-size: 10px; color: #f4f4f4; padding: 11px 0; line-height: 12px;'>Lojas pelo Brasil</td>
                                </tr>
                            </table>
                        </a>
                    </td>
                    <td><img src='http://trunk.nagem.com.br/util/artefatos/asset/n/1121721392427/img/layout/email/img-separador-menu.png' height='25' /></td>
                    <td>
                        <table>
                            <tr>
                                <td valign='top'><img style='padding: 8px 0;' src='http://trunk.nagem.com.br/util/artefatos/asset/n/3611721392427/img/layout/email/ebit-logo.png' height='20'></td>
                                <td valign='top' style='text-align: left; width: 75px; font-size: 10px; color: #f4f4f4; padding: 8px 0; line-height: 12px;'>Loja Avaliada <br />no E-Bit</td>
                            </tr>
                        </table>
                    </td>
                    <td><img src='http://trunk.nagem.com.br/util/artefatos/asset/n/1121721392427/img/layout/email/img-separador-menu.png' height='25'></td>
                    <td>
                        <table>
                            <tr>
                                <td valign='top'><img style='padding: 10px 0;' src='http://trunk.nagem.com.br/util/artefatos/asset/n/3841721392427/img/layout/email/sac.png' /></td>
                                <td valign='top' style='text-align:left; width:65px; font-size:10px; color:#f4f4f4; padding: 9px 0; line-height: 12px;'>SAC Site<br><a href='tel:0800-0802121' style='font-size:10px; color:#f4f4f4; text-decoration: none;'>0800 0802121</a></td>
                            </tr>
                        </table>
                    </td>
                    <td><img src='http://trunk.nagem.com.br/util/artefatos/asset/n/1121721392427/img/layout/email/img-separador-menu.png' height='25'></td>
                    <td>
                        <table>
                            <tr>
                                <td valign='top'><span style='font-size: 18px; font-weight: bold; color: #ffffff;'><img src='http://trunk.nagem.com.br/util/artefatos/asset/n/4011721392427/img/layout/email/cd.png' /></span></td>
                                <td valign='top' style='text-align: left; width: 30px; font-size: 10px; color: #ffffff; line-height: 12px;'><a style='font-size:10px;color:#f4f4f4;text-decoration: none;' target='_blank' href='http://trunk.nagem.com.br/institucional/nossaslojas/'>Lojas <br>e CDs</a></td>
                            </tr>
                        </table>
                    </td>
                </table>
            </td>
        </tr>
        <tr>
        <tr>
            <td>
                <table width=96% border=0 align=center>
                    <td align="left">
                        </p>
                        <b><?= htmlspecialchars($customer) ?></b>
                        <p>Obrigado por comprar na Nagem. Confirmamos seu <b>pedido <?= htmlspecialchars($order) ?></b> realizado em <?= htmlspecialchars($order_date) ?>.</p>
                        <p><b>Forma de Pagamento:</b><br> <?= htmlspecialchars($payment_method) ?></br></p>
                        <p><b><?= htmlspecialchars($delivery_type) ?></b> estará sujeira ao reconhecimento do pagamento a depender da modalidade realizada.</p>
                        <p><b>Previsão de Entrega:</b> <?= htmlspecialchars($delivery_forecast) ?></p>
                        <p><b>Rastreamento:</b> <a href='<?= htmlspecialchars($order_tracking) ?>'>Clique aqui para reastrear seu Pedido</a></p>
                        <p>Caso tenha alguma dúvida contate o Vendedor que fez seu atendimento.</p>
                        <p>Equipe Nagem</p>
                        </p>
                </table>
        </tr>
        </td>
        <tr>
            <td>
                <table width="96%" align="center" style="border-collapse: collapse; margin: 0 auto; background-color: #ffffff;">
                    <thead>
                        <tr style='background-color:#0046B4;color:#ffffff;text-align:left;'>
                            <th>Descrição dos Produtos</th>
                            <th>Qtd.</th>
                            <th>Preço</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody style='background-color:#ffffff;color:#000;text-align:left;'>
                        <tr>
                            <td>
                                </p>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <?php foreach ($products as $product): ?>
                            <tr>
                                <td><?= htmlspecialchars($product['Product Description']) ?></td>
                                <td><?= htmlspecialchars($product['Quantity']) ?></td>
                                <td><?= formatarValorMonetario(htmlspecialchars($product['Price'])) ?></td>
                                <td><?= formatarValorMonetario(htmlspecialchars($product['Total'])) ?></td>
                            </tr>
                        <?php endforeach; ?>
                        <tr>
                            <td>
                                </p>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                    <tfoot style='background-color:#e7eff6;color:#4b86b4;text-align:left;'>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Itens:</td>
                            <td><?= formatarValorMonetario(htmlspecialchars($summary['Itens'])) ?></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Garantias:</td>
                            <td><?= formatarValorMonetario(htmlspecialchars($summary['Warranties'])) ?></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Frete:</td>
                            <td><?= formatarValorMonetario(htmlspecialchars($summary['Shipping'])) ?></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Total:</td>
                            <td><?= formatarValorMonetario(htmlspecialchars($summary['Total'])) ?></td>
                        </tr>
                    </tfoot>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                </p>
            </td>
        </tr>
    </table>
</body>

</html>